algoritmo "Funções"
var
   abs_, exp_, int_, raiz, pi_, sen_, cos_, tan_ : real
inicio

   abs_ <- abs(-10)
   exp_ <- exp(4,2)
   int_ <- int(55.6)
   raiz <- raizq(49)
   pi_ <- pi
   sen_ <- sen(3*pi/2)
   cos_ <- cos(pi)
   tan_ <- tan(pi/4)

   escreval("Absoluto de (-10) =", abs_)
   escreval("(4,1) ou 4 elevado a 2 =", exp_)
   escreval("Inteiro de 55.6 =", int_)
   escreval("Raiz de 49 =", raiz)
   escreval("Valor de pi =", pi_)
   escreval("Seno de (3.pi/2) ou (270°) =", sen_)
   escreval("Cosseno de (pi) ou (180°) =", cos_)
   escreval("Tangente de (pi/4) ou (90°) =", tan_)

fimalgoritmo